name: lint

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: Link code with Eslint
        run: npm run lint
